//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiHiringItm.CORE.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiHiringItm.CORE.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentran archivos para adjuntar al correo .
        /// </summary>
        internal static string ATTACHMENTEMPTY {
            get {
                return ResourceManager.GetString("ATTACHMENTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador no contiene la  estructura valida.
        /// </summary>
        internal static string GUIDNOTVALID {
            get {
                return ResourceManager.GetString("GUIDNOTVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro información.
        /// </summary>
        internal static string INFORMATIONEMPTY {
            get {
                return ResourceManager.GetString("INFORMATIONEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación envida exitosamente.
        /// </summary>
        internal static string MAILSENDSUCCESS {
            get {
                return ResourceManager.GetString("MAILSENDSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información registra exitosamnete.
        /// </summary>
        internal static string REGISTERSUCCESSFULL {
            get {
                return ResourceManager.GetString("REGISTERSUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algo salió mal. por favor, vuelva a intentarlo.
        /// </summary>
        internal static string TRYAGAINT {
            get {
                return ResourceManager.GetString("TRYAGAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información actualizada exitosamente.
        /// </summary>
        internal static string UPDATESUCCESSFULL {
            get {
                return ResourceManager.GetString("UPDATESUCCESSFULL", resourceCulture);
            }
        }
    }
}
