//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiHiringItm.CORE.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApiHiringItm.CORE.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentran archivos para adjuntar al correo .
        /// </summary>
        internal static string ATTACHMENTEMPTY {
            get {
                return ResourceManager.GetString("ATTACHMENTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alguno de los valores ingresados no es correcto.
        /// </summary>
        internal static string AUTENTICATEFIELDERROR {
            get {
                return ResourceManager.GetString("AUTENTICATEFIELDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autenticación exitosa.
        /// </summary>
        internal static string AUTENTICATERESPONSE {
            get {
                return ResourceManager.GetString("AUTENTICATERESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya esta registrado el banco.
        /// </summary>
        internal static string BANKEXIST {
            get {
                return ResourceManager.GetString("BANKEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Eliminado exitosamente.
        /// </summary>
        internal static string DELETESUCCESS {
            get {
                return ResourceManager.GetString("DELETESUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo ya se ha actualizado, vuelva arequerir cambio de clave.
        /// </summary>
        internal static string DISABLEMAIL {
            get {
                return ResourceManager.GetString("DISABLEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Docuemnto generado exitosamente.
        /// </summary>
        internal static string DOCUMENTGENERATE {
            get {
                return ResourceManager.GetString("DOCUMENTGENERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el correo o contraseña.
        /// </summary>
        internal static string ERRORAUTENTICATE {
            get {
                return ResourceManager.GetString("ERRORAUTENTICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información del detalle del archivo fallo al registrarse.
        /// </summary>
        internal static string ERRORDETAILFILE {
            get {
                return ResourceManager.GetString("ERRORDETAILFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al cargar el excel porque esta imcompleto.
        /// </summary>
        internal static string ERRORUPLOADEXCEL {
            get {
                return ResourceManager.GetString("ERRORUPLOADEXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la información esta incompleta para generar el documento.
        /// </summary>
        internal static string EXCELEMPTY {
            get {
                return ResourceManager.GetString("EXCELEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excel importado exitosamente.
        /// </summary>
        internal static string EXCELIMPORTSUCCESS {
            get {
                return ResourceManager.GetString("EXCELIMPORTSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador no contiene la  estructura valida.
        /// </summary>
        internal static string GUIDNOTVALID {
            get {
                return ResourceManager.GetString("GUIDNOTVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro la firma del usuario para el mensaje.
        /// </summary>
        internal static string IMAGEUSERMESSAGE {
            get {
                return ResourceManager.GetString("IMAGEUSERMESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontro información.
        /// </summary>
        internal static string INFORMATIONEMPTY {
            get {
                return ResourceManager.GetString("INFORMATIONEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo proporcionado no esta registrado.
        /// </summary>
        internal static string MAILNOTEXIST {
            get {
                return ResourceManager.GetString("MAILNOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación envida exitosamente.
        /// </summary>
        internal static string MAILSENDSUCCESS {
            get {
                return ResourceManager.GetString("MAILSENDSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al registrar la información de pago.
        /// </summary>
        internal static string PAYMENTERROR {
            get {
                return ResourceManager.GetString("PAYMENTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información registra exitosamnete.
        /// </summary>
        internal static string REGISTERSUCCESSFULL {
            get {
                return ResourceManager.GetString("REGISTERSUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Restablecimiento de contraseña enviado! Recibirás un correo electrónico si estás registrado en nuestro sistema..
        /// </summary>
        internal static string RESETPASSWORDSUCCESS {
            get {
                return ResourceManager.GetString("RESETPASSWORDSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña restaurada exitosamente.
        /// </summary>
        internal static string RESETSUCCESS {
            get {
                return ResourceManager.GetString("RESETSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron fechas limite para la entrega de los documentos|.
        /// </summary>
        internal static string TERMDATENOTFOUND {
            get {
                return ResourceManager.GetString("TERMDATENOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algo salió mal. por favor, vuelva a intentarlo.
        /// </summary>
        internal static string TRYAGAINT {
            get {
                return ResourceManager.GetString("TRYAGAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información actualizada exitosamente.
        /// </summary>
        internal static string UPDATESUCCESSFULL {
            get {
                return ResourceManager.GetString("UPDATESUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un usuario registrado con ese correo.
        /// </summary>
        internal static string USEREXIST {
            get {
                return ResourceManager.GetString("USEREXIST", resourceCulture);
            }
        }
    }
}
