// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class AssigmentContract
    {
        public Guid Id { get; set; }
        public Guid? ContractId { get; set; }
        public Guid UserId { get; set; }
        public Guid RollId { get; set; }
        public Guid AssignmentType { get; set; }

        public virtual AssignmentType AssignmentTypeNavigation { get; set; }
        public virtual ContractFolder Contract { get; set; }
        public virtual Roll Roll { get; set; }
        public virtual UserT User { get; set; }
    }
}