// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class ChangeContractContractor
    {
        public Guid Id { get; set; }
        public Guid? DetailContractor { get; set; }
        public string NombreElemento { get; set; }
        public string ObligacionesGenerales { get; set; }
        public string ObligacionesEspecificas { get; set; }
        public int? CantidadDias { get; set; }
        public decimal? ValorUnidad { get; set; }
        public decimal? ValorTotal { get; set; }
        public decimal? ValorTotalContratista { get; set; }
        public decimal? ValorPorDiaContratista { get; set; }
        public decimal? Recursos { get; set; }
        public decimal? ValorPorDia { get; set; }
        public Guid? CpcId { get; set; }
        public bool? Modificacion { get; set; }
        public string Consecutivo { get; set; }
        public string ObjetoElemento { get; set; }
        public string PerfilRequerido { get; set; }
        public DateTime? FechaInicioAdicion { get; set; }
        public DateTime? FechaFinAdicion { get; set; }
        public DateTime? RegisterDate { get; set; }
        public Guid? MinuteType { get; set; }
        public string NoAdicion { get; set; }

        public virtual DetailContractor DetailContractorNavigation { get; set; }
        public virtual MinuteType MinuteTypeNavigation { get; set; }
    }
}