// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Component
    {
        public Component()
        {
            Activity = new HashSet<Activity>();
            DetailProjectContractor = new HashSet<DetailProjectContractor>();
            ElementComponent = new HashSet<ElementComponent>();
        }

        public Guid Id { get; set; }
        public string NombreComponente { get; set; }
        public Guid ContractId { get; set; }

        public virtual ContractFolder Contract { get; set; }
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual ICollection<DetailProjectContractor> DetailProjectContractor { get; set; }
        public virtual ICollection<ElementComponent> ElementComponent { get; set; }
    }
}