// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Componente
    {
        public Componente()
        {
            Actividad = new HashSet<Actividad>();
            DetailProjectContractor = new HashSet<DetailProjectContractor>();
            ElementosComponente = new HashSet<ElementosComponente>();
        }

        public Guid Id { get; set; }
        public string NombreComponente { get; set; }
        public Guid IdContrato { get; set; }

        public virtual ProjectFolder IdContratoNavigation { get; set; }
        public virtual ICollection<Actividad> Actividad { get; set; }
        public virtual ICollection<DetailProjectContractor> DetailProjectContractor { get; set; }
        public virtual ICollection<ElementosComponente> ElementosComponente { get; set; }
    }
}