// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Componente
    {
        public Componente()
        {
            ElementosComponente = new HashSet<ElementosComponente>();
            ProfessionalRol = new HashSet<ProfessionalRol>();
        }

        public int Id { get; set; }
        public string NombreComponente { get; set; }
        public int IdContrato { get; set; }
        public string Rubro { get; set; }
        public string NombreRubro { get; set; }

        public virtual ProjectFolder IdContratoNavigation { get; set; }
        public virtual ICollection<ElementosComponente> ElementosComponente { get; set; }
        public virtual ICollection<ProfessionalRol> ProfessionalRol { get; set; }
    }
}