// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Component
    {
        public int Id { get; set; }
        public int? PlaningId { get; set; }
        public int? ContractorCant { get; set; }
        public decimal? UnitValue { get; set; }
        public decimal? TotalValue { get; set; }

        public virtual Planning Planing { get; set; }
    }
}