// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class ContractorPayments
    {
        public Guid Id { get; set; }
        public Guid ContractorId { get; set; }
        public Guid ContractId { get; set; }
        public Guid? UserId { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public string DescriptionPayment { get; set; }
        public decimal? Paymentcant { get; set; }
        public bool? CashPayment { get; set; }

        public virtual ContractFolder Contract { get; set; }
        public virtual Contractor Contractor { get; set; }
        public virtual UserT User { get; set; }
    }
}