// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class ContractorPayments
    {
        public int Id { get; set; }
        public int? ContractorId { get; set; }
        public int? UserId { get; set; }
        public decimal? MonthPayment { get; set; }
        public DateTime? RegisterDate { get; set; }
        public DateTime? ModifyDate { get; set; }
        public decimal? Paymentcant { get; set; }
        public bool? CashPayment { get; set; }

        public virtual Contractor Contractor { get; set; }
        public virtual UserT User { get; set; }
    }
}