// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class CpcType
    {
        public CpcType()
        {
            ElementComponent = new HashSet<ElementComponent>();
        }

        public Guid Id { get; set; }
        public string CpcNumber { get; set; }
        public string CpcName { get; set; }

        public virtual ICollection<ElementComponent> ElementComponent { get; set; }
    }
}