// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class DetalleFile
    {
        public Guid Id { get; set; }
        public Guid FileId { get; set; }
        public string Reason { get; set; }
        public string Observation { get; set; }

        public virtual Files File { get; set; }
    }
}