// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class DetalleContrato
    {
        public Guid Id { get; set; }
        public Guid? ContractId { get; set; }
        public DateTime? FechaContrato { get; set; }
        public DateTime? FechaFinalizacion { get; set; }
        public string NoAdicion { get; set; }
        public string TipoContrato { get; set; }

        public virtual ProjectFolder Contract { get; set; }
    }
}