// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class DetailProjectContractor
    {
        public Guid Id { get; set; }
        public Guid? ContractId { get; set; }
        public Guid? ContractorId { get; set; }
        public Guid? HiringDataId { get; set; }
        public Guid? ElementId { get; set; }
        public Guid? ComponenteId { get; set; }

        public virtual Componente Componente { get; set; }
        public virtual ProjectFolder Contract { get; set; }
        public virtual Contractor Contractor { get; set; }
        public virtual ElementosComponente Element { get; set; }
        public virtual HiringData HiringData { get; set; }
    }
}