// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class DetailType
    {
        public DetailType()
        {
            DetailContract = new HashSet<DetailContract>();
        }

        public Guid Id { get; set; }
        public string DetailTypeDescripcion { get; set; }
        public string Code { get; set; }

        public virtual ICollection<DetailContract> DetailContract { get; set; }
    }
}