// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Detailpayroll
    {
        public Guid Id { get; set; }
        public string StatusPayroll { get; set; }
        public Guid? PayrollContract { get; set; }
        public int Consecutive { get; set; }
        public bool GeneratedSatisfaction { get; set; }
        public DateTime? RegisterDate { get; set; }

        public virtual PayrollContract PayrollContractNavigation { get; set; }
    }
}