// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class DetalleContrato
    {
        public int Id { get; set; }
        public Guid? Idcontrato { get; set; }
        public DateTime? FechaContrato { get; set; }
        public DateTime? FechaFinalizacion { get; set; }
        public DateTime? FechaInicioAmpliacion { get; set; }
        public DateTime? FechaDeTerminacionAmpliacion { get; set; }
        public string NoAdicion { get; set; }
        public bool? Modificacion { get; set; }
        public string TipoContrato { get; set; }

        public virtual ProjectFolder IdcontratoNavigation { get; set; }
    }
}