// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class ElementType
    {
        public ElementType()
        {
            ElementComponent = new HashSet<ElementComponent>();
        }

        public Guid Id { get; set; }
        public string ElementType1 { get; set; }
        public string Code { get; set; }

        public virtual ICollection<ElementComponent> ElementComponent { get; set; }
    }
}