// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class EntityHealth
    {
        public EntityHealth()
        {
            ContractorAfpNavigation = new HashSet<Contractor>();
            ContractorArlNavigation = new HashSet<Contractor>();
            ContractorEpsNavigation = new HashSet<Contractor>();
        }

        public Guid Id { get; set; }
        public string EntityHealthDescription { get; set; }
        public string Code { get; set; }

        public virtual ICollection<Contractor> ContractorAfpNavigation { get; set; }
        public virtual ICollection<Contractor> ContractorArlNavigation { get; set; }
        public virtual ICollection<Contractor> ContractorEpsNavigation { get; set; }
    }
}