// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Files
    {
        public Files()
        {
            DetailFile = new HashSet<DetailFile>();
        }

        public Guid Id { get; set; }
        public Guid ContractorId { get; set; }
        public Guid? ContractId { get; set; }
        public string FilesName { get; set; }
        public string Filedata { get; set; }
        public Guid? FileType { get; set; }
        public string DocumentType { get; set; }
        public string DescriptionFile { get; set; }
        public Guid? UserId { get; set; }
        public DateTime? RegisterDate { get; set; }
        public string TypeFilePayment { get; set; }
        public string MonthPayment { get; set; }
        public Guid? FolderId { get; set; }
        public bool? Passed { get; set; }

        public virtual FileType FileTypeNavigation { get; set; }
        public virtual UserT User { get; set; }
        public virtual ICollection<DetailFile> DetailFile { get; set; }
    }
}