// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Files
    {
        public int Id { get; set; }
        public int IdContractor { get; set; }
        public string FilesName { get; set; }
        public string Filename { get; set; }
        public string FileType { get; set; }
        public int IdUser { get; set; }

        public virtual Contractor IdContractorNavigation { get; set; }
        public virtual UserT IdUserNavigation { get; set; }
    }
}