// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Files
    {
        public int Id { get; set; }
        public int ContractorId { get; set; }
        public int FolderId { get; set; }
        public string FilesName { get; set; }
        public string Filedata { get; set; }
        public string TypeFile { get; set; }
        public string DescriptionFile { get; set; }
        public int UserId { get; set; }
        public DateTime? RegisterDate { get; set; }
        public DateTime? ModifyDate { get; set; }
        public bool? Passed { get; set; }

        public virtual FolderContractor Folder { get; set; }
        public virtual UserT User { get; set; }
    }
}