// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class FileType
    {
        public FileType()
        {
            Files = new HashSet<Files>();
        }

        public Guid Id { get; set; }
        public string FileType1 { get; set; }
        public string Code { get; set; }

        public virtual ICollection<Files> Files { get; set; }
    }
}