// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class FolderType
    {
        public FolderType()
        {
            Folder = new HashSet<Folder>();
        }

        public Guid Id { get; set; }
        public string FolderTypeDescription { get; set; }
        public string Code { get; set; }

        public virtual ICollection<Folder> Folder { get; set; }
    }
}