// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Folder
    {
        public Folder()
        {
            Files = new HashSet<Files>();
        }

        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public Guid? ContractorId { get; set; }
        public Guid? ContractId { get; set; }
        public string FolderName { get; set; }
        public string DescriptionProject { get; set; }
        public DateTime? RegisterDate { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string TypeFolder { get; set; }

        public virtual ContractFolder Contract { get; set; }
        public virtual Contractor Contractor { get; set; }
        public virtual ICollection<Files> Files { get; set; }
    }
}