// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class FolderContractor
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Guid? ContractorId { get; set; }
        public Guid? ContractId { get; set; }
        public string FolderName { get; set; }
        public string DescriptionProject { get; set; }
        public DateTime? RegisterDate { get; set; }
        public DateTime? ModifyDate { get; set; }

        public virtual ProjectFolder Contract { get; set; }
        public virtual Contractor Contractor { get; set; }
    }
}