// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class HiringData
    {
        public int Id { get; set; }
        public int? ContractorId { get; set; }
        public int? UserId { get; set; }
        public DateTime? FechaFinalizacionConvenio { get; set; }
        public string Actividad { get; set; }
        public string Contrato { get; set; }
        public string Compromiso { get; set; }
        public DateTime? FechaExaPreocupacional { get; set; }
        public string SupervisorItm { get; set; }
        public string CargoSupervisorItm { get; set; }
        public DateTime? FechaDeInicioProyectado { get; set; }
        public DateTime? FechaRealDeInicio { get; set; }
        public string Ejecucion { get; set; }
        public string ActaComite { get; set; }
        public DateTime? FechaDeComite { get; set; }
        public bool? RequierePoliza { get; set; }
        public string NoPoliza { get; set; }
        public DateTime? VigenciaInicial { get; set; }
        public DateTime? VigenciaFinal { get; set; }
        public DateTime? FechaExpedicionPoliza { get; set; }
        public decimal? ValorAsegurado { get; set; }
        public int? Nivel { get; set; }
        public string Rubro { get; set; }
        public string NombreRubro { get; set; }
        public string FuenteRubro { get; set; }
        public string Cdp { get; set; }

        public virtual Contractor Contractor { get; set; }
        public virtual UserT User { get; set; }
    }
}