// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class MinuteType
    {
        public MinuteType()
        {
            ChangeContractContractor = new HashSet<ChangeContractContractor>();
        }

        public Guid Id { get; set; }
        public string MinuteTypeDescription { get; set; }
        public string Code { get; set; }

        public virtual ICollection<ChangeContractContractor> ChangeContractContractor { get; set; }
    }
}