// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class NewnessContractor
    {
        public Guid Id { get; set; }
        public Guid ContractorId { get; set; }
        public string NewnessDescripcion { get; set; }
        public Guid NewnessType { get; set; }
        public Guid ContractId { get; set; }
        public DateTime RegisterDate { get; set; }

        public virtual ContractFolder Contract { get; set; }
        public virtual Contractor Contractor { get; set; }
        public virtual NewnessType NewnessTypeNavigation { get; set; }
    }
}