// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class NewnessContractor
    {
        public Guid Id { get; set; }
        public Guid? ContractorId { get; set; }
        public string DescripcionNovedad { get; set; }
        public string TipoNovedad { get; set; }
        public Guid? ContractId { get; set; }

        public virtual ProjectFolder Contract { get; set; }
        public virtual Contractor Contractor { get; set; }
    }
}