// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class PayrollContract
    {
        public PayrollContract()
        {
            Detailpayroll = new HashSet<Detailpayroll>();
        }

        public Guid Id { get; set; }
        public Guid? ContractId { get; set; }
        public int Consecutive { get; set; }
        public decimal? GastosOperativos { get; set; }
        public decimal? ValorSubTotal { get; set; }
        public decimal? ResourceContract { get; set; }

        public virtual ContractFolder Contract { get; set; }
        public virtual ICollection<Detailpayroll> Detailpayroll { get; set; }
    }
}