// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Planning
    {
        public int Id { get; set; }
        public string Componente { get; set; }
        public decimal? HonorariosMensuales { get; set; }
        public string Profesional { get; set; }
        public string Laboral { get; set; }
        public decimal? ValorTotal { get; set; }
        public string Objeto { get; set; }
    }
}