// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class PorcenterSecurity
    {
        public Guid Id { get; set; }
        public decimal PercentageValue { get; set; }
        public string Code { get; set; }
    }
}