// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class ProfessionalRol
    {
        public int Id { get; set; }
        public int? ComponentId { get; set; }
        public int? ContractorCant { get; set; }
        public decimal? UnitValue { get; set; }
        public decimal? Total { get; set; }
        public decimal? DayValue { get; set; }
        public int? Contractorduration { get; set; }

        public virtual Componente Component { get; set; }
    }
}