// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class ProjectFolder
    {
        public ProjectFolder()
        {
            Contractor = new HashSet<Contractor>();
        }

        public int Id { get; set; }
        public int IdUser { get; set; }
        public string CompanyName { get; set; }
        public string ProjectName { get; set; }
        public DateTime? RegisterDate { get; set; }
        public DateTime? ModifyDate { get; set; }

        public virtual UserT IdUserNavigation { get; set; }
        public virtual ICollection<Contractor> Contractor { get; set; }
    }
}