// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class RecursiveContractor
    {
        public int Id { get; set; }
        public int? IdFile { get; set; }
        public int? IdFolder { get; set; }
        public int? IdUser { get; set; }
        public int? IdContractorStudy { get; set; }
        public int? IdHiringdata { get; set; }
        public int? IdContractor { get; set; }

        public virtual Contractor IdContractorNavigation { get; set; }
        public virtual ContractorStudy IdContractorStudyNavigation { get; set; }
        public virtual Files IdFileNavigation { get; set; }
        public virtual ProjectFolder IdFolderNavigation { get; set; }
        public virtual Hiringdata IdHiringdataNavigation { get; set; }
        public virtual UserT IdUserNavigation { get; set; }
    }
}