// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class Roll
    {
        public Roll()
        {
            UserT = new HashSet<UserT>();
        }

        public int Id { get; set; }
        public string RollName { get; set; }

        public virtual ICollection<UserT> UserT { get; set; }
    }
}