// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class SessionPanel
    {
        public Guid Id { get; set; }
        public string PanelCode { get; set; }
        public Guid? UserId { get; set; }
        public DateTime? StartSessionDate { get; set; }
        public DateTime? FinalSessionDate { get; set; }
        public bool? Activate { get; set; }
        public Guid? ContractId { get; set; }
        public Guid? ContractorId { get; set; }

        public virtual Contractor Contractor { get; set; }
        public virtual UserT User { get; set; }
    }
}