// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class SharedData
    {
        public Guid Id { get; set; }
        public string TypeDataShare { get; set; }
        public string DescriptionData { get; set; }
        public string TypedataRegistered { get; set; }
        public string AdditionalData { get; set; }
    }
}