// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class StatusContractor
    {
        public StatusContractor()
        {
            DetailProjectContractor = new HashSet<DetailProjectContractor>();
        }

        public Guid Id { get; set; }
        public string StatusContractor1 { get; set; }
        public string Code { get; set; }

        public virtual ICollection<DetailProjectContractor> DetailProjectContractor { get; set; }
    }
}