// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class StatusContractor
    {
        public StatusContractor()
        {
            DetailContractor = new HashSet<DetailContractor>();
        }

        public Guid Id { get; set; }
        public string StatusContractorDescription { get; set; }
        public string Code { get; set; }

        public virtual ICollection<DetailContractor> DetailContractor { get; set; }
    }
}