// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class StatusFile
    {
        public StatusFile()
        {
            DetailFile = new HashSet<DetailFile>();
        }

        public Guid Id { get; set; }
        public string StatusFile1 { get; set; }
        public string Code { get; set; }

        public virtual ICollection<DetailFile> DetailFile { get; set; }
    }
}