// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class TermContract
    {
        public Guid Id { get; set; }
        public Guid DetailContractor { get; set; }
        public DateTime TermDate { get; set; }
        public DateTime? StartDate { get; set; }
        public Guid TermType { get; set; }

        public virtual DetailContractor DetailContractorNavigation { get; set; }
        public virtual TermType TermTypeNavigation { get; set; }
    }
}