// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class TermContract
    {
        public Guid Id { get; set; }
        public Guid DetailContract { get; set; }
        public DateTime FechaTermino { get; set; }
        public DateTime? FechaInicio { get; set; }
        public Guid TermType { get; set; }

        public virtual DetailContract DetailContractNavigation { get; set; }
        public virtual TermType TermTypeNavigation { get; set; }
    }
}