// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class TermType
    {
        public TermType()
        {
            TermContract = new HashSet<TermContract>();
        }

        public Guid Id { get; set; }
        public string TermDescription { get; set; }
        public string Code { get; set; }

        public virtual ICollection<TermContract> TermContract { get; set; }
    }
}