// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class TypeUserFile
    {
        public TypeUserFile()
        {
            UserFile = new HashSet<UserFile>();
        }

        public Guid Id { get; set; }
        public string TypeFile { get; set; }
        public string Code { get; set; }

        public virtual ICollection<UserFile> UserFile { get; set; }
    }
}