// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class UserFile
    {
        public UserFile()
        {
            UserT = new HashSet<UserT>();
        }

        public Guid Id { get; set; }
        public Guid? TypeUserFile { get; set; }
        public string FirmData { get; set; }
        public Guid? RollId { get; set; }
        public string OwnerFirm { get; set; }
        public string UserfileName { get; set; }

        public virtual Roll Roll { get; set; }
        public virtual TypeUserFile TypeUserFileNavigation { get; set; }
        public virtual ICollection<UserT> UserT { get; set; }
    }
}