// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class UserT
    {
        public UserT()
        {
            ContractFolder = new HashSet<ContractFolder>();
            Contractor = new HashSet<Contractor>();
            ContractorPayments = new HashSet<ContractorPayments>();
            Files = new HashSet<Files>();
            HiringData = new HashSet<HiringData>();
            UserFirm = new HashSet<UserFirm>();
        }

        public Guid Id { get; set; }
        public string UserName { get; set; }
        public string Avatar { get; set; }
        public string Professionalposition { get; set; }
        public string UserPassword { get; set; }
        public Guid RollId { get; set; }
        public string UserEmail { get; set; }
        public string PhoneNumber { get; set; }
        public string Identification { get; set; }

        public virtual Roll Roll { get; set; }
        public virtual ICollection<ContractFolder> ContractFolder { get; set; }
        public virtual ICollection<Contractor> Contractor { get; set; }
        public virtual ICollection<ContractorPayments> ContractorPayments { get; set; }
        public virtual ICollection<Files> Files { get; set; }
        public virtual ICollection<HiringData> HiringData { get; set; }
        public virtual ICollection<UserFirm> UserFirm { get; set; }
    }
}