// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiHiringItm.MODEL.Entities
{
    public partial class UserFirm
    {
        public Guid Id { get; set; }
        public Guid? UserId { get; set; }
        public string FirmUser { get; set; }
        public string FirmData { get; set; }

        public virtual UserT User { get; set; }
    }
}