// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WebApiHiringItm.MODEL.Entities;

namespace WebApiHiringItm.CONTEXT.Context
{
    public partial class HiringContext : DbContext
    {
        public HiringContext()
        {
        }

        public HiringContext(DbContextOptions<HiringContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AcademicInformation> AcademicInformation { get; set; }
        public virtual DbSet<AccountType> AccountType { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<Component> Component { get; set; }
        public virtual DbSet<ContractFolder> ContractFolder { get; set; }
        public virtual DbSet<Contractor> Contractor { get; set; }
        public virtual DbSet<ContractorPayments> ContractorPayments { get; set; }
        public virtual DbSet<CpcType> CpcType { get; set; }
        public virtual DbSet<DetailContract> DetailContract { get; set; }
        public virtual DbSet<DetailFile> DetailFile { get; set; }
        public virtual DbSet<DetailProjectContractor> DetailProjectContractor { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<EconomicdataContractor> EconomicdataContractor { get; set; }
        public virtual DbSet<ElementComponent> ElementComponent { get; set; }
        public virtual DbSet<ElementType> ElementType { get; set; }
        public virtual DbSet<EmptityHealth> EmptityHealth { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<Folder> Folder { get; set; }
        public virtual DbSet<FolderType> FolderType { get; set; }
        public virtual DbSet<HiringData> HiringData { get; set; }
        public virtual DbSet<MinuteType> MinuteType { get; set; }
        public virtual DbSet<NewnessContractor> NewnessContractor { get; set; }
        public virtual DbSet<NewnessType> NewnessType { get; set; }
        public virtual DbSet<Roll> Roll { get; set; }
        public virtual DbSet<SharedData> SharedData { get; set; }
        public virtual DbSet<StatusContract> StatusContract { get; set; }
        public virtual DbSet<StatusContractor> StatusContractor { get; set; }
        public virtual DbSet<StatusFile> StatusFile { get; set; }
        public virtual DbSet<UserFirm> UserFirm { get; set; }
        public virtual DbSet<UserT> UserT { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AcademicInformation>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Institution)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.TypeAcademicInformation)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.ContractorNavigation)
                    .WithMany(p => p.AcademicInformation)
                    .HasForeignKey(d => d.Contractor)
                    .HasConstraintName("FK__AcademicI__Contr__5EBF139D");
            });

            modelBuilder.Entity<AccountType>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.AccountType1)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("AccountType");
            });

            modelBuilder.Entity<Activity>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.NombreActividad)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Component)
                    .WithMany(p => p.Activity)
                    .HasForeignKey(d => d.ComponentId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Activity__Compon__6383C8BA");
            });

            modelBuilder.Entity<Banks>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.BankName)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Component>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.NombreComponente)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.HasOne(d => d.Contract)
                    .WithMany(p => p.Component)
                    .HasForeignKey(d => d.ContractId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Component__Contr__6EF57B66");
            });

            modelBuilder.Entity<ContractFolder>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CompanyName)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.FuenteRubro).HasMaxLength(100);

                entity.Property(e => e.GastosOperativos).HasColumnType("money");

                entity.Property(e => e.NombreRubro).HasMaxLength(50);

                entity.Property(e => e.NumberProject)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.Project).HasMaxLength(30);

                entity.Property(e => e.ProjectName)
                    .IsRequired()
                    .HasMaxLength(300);

                entity.Property(e => e.Rubro).HasMaxLength(30);

                entity.Property(e => e.ValorContrato).HasColumnType("money");

                entity.Property(e => e.ValorSubTotal).HasColumnType("money");

                entity.HasOne(d => d.StatusContract)
                    .WithMany(p => p.ContractFolder)
                    .HasForeignKey(d => d.StatusContractId)
                    .HasConstraintName("FK__ContractF__Statu__7C4F7684");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.ContractFolder)
                    .HasForeignKey(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__ContractF__UserI__628FA481");
            });

            modelBuilder.Entity<Contractor>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Apellido)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Barrio)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Celular)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.ClaveUsuario).HasMaxLength(15);

                entity.Property(e => e.Correo)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.CuentaBancaria).HasMaxLength(100);

                entity.Property(e => e.Departamento)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Direccion)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.FechaActualizacion).HasColumnType("date");

                entity.Property(e => e.FechaCreacion).HasColumnType("date");

                entity.Property(e => e.FechaNacimiento).HasColumnType("date");

                entity.Property(e => e.Genero)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Identificacion)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.LugarExpedicion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Municipio)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Nacionalidad)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Telefono)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.EntidadCuentaBancariaNavigation)
                    .WithMany(p => p.Contractor)
                    .HasForeignKey(d => d.EntidadCuentaBancaria)
                    .HasConstraintName("FK__Contracto__Entid__619B8048");

                entity.HasOne(d => d.TipoCuentaNavigation)
                    .WithMany(p => p.Contractor)
                    .HasForeignKey(d => d.TipoCuenta)
                    .HasConstraintName("FK__Contracto__TipoC__60A75C0F");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Contractor)
                    .HasForeignKey(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Contracto__UserI__68487DD7");
            });

            modelBuilder.Entity<ContractorPayments>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.FromDate).HasColumnType("date");

                entity.Property(e => e.Paymentcant).HasColumnType("money");

                entity.Property(e => e.ToDate).HasColumnType("date");

                entity.HasOne(d => d.Contract)
                    .WithMany(p => p.ContractorPayments)
                    .HasForeignKey(d => d.ContractId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Contracto__Contr__72C60C4A");

                entity.HasOne(d => d.Contractor)
                    .WithMany(p => p.ContractorPayments)
                    .HasForeignKey(d => d.ContractorId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Contracto__Contr__70DDC3D8");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.ContractorPayments)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK__Contracto__UserI__71D1E811");
            });

            modelBuilder.Entity<CpcType>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CpcName).HasMaxLength(200);

                entity.Property(e => e.CpcNumber).HasMaxLength(100);
            });

            modelBuilder.Entity<DetailContract>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.ContractId).HasColumnName("contractId");

                entity.Property(e => e.FechaContrato).HasColumnType("date");

                entity.Property(e => e.FechaFinalizacion).HasColumnType("date");

                entity.Property(e => e.NoAdicion).HasMaxLength(20);

                entity.Property(e => e.TipoContrato)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.Contract)
                    .WithMany(p => p.DetailContract)
                    .HasForeignKey(d => d.ContractId)
                    .HasConstraintName("FK__DetailCon__contr__778AC167");
            });

            modelBuilder.Entity<DetailFile>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Observation).IsUnicode(false);

                entity.Property(e => e.Reason)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.RegisterDate).HasColumnType("date");

                entity.Property(e => e.StatusFileId).HasColumnName("statusFileId");

                entity.HasOne(d => d.File)
                    .WithMany(p => p.DetailFile)
                    .HasForeignKey(d => d.FileId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__DetailFil__FileI__03F0984C");

                entity.HasOne(d => d.StatusFile)
                    .WithMany(p => p.DetailFile)
                    .HasForeignKey(d => d.StatusFileId)
                    .HasConstraintName("FK__DetailFil__statu__02FC7413");
            });

            modelBuilder.Entity<DetailProjectContractor>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.ContractId).HasColumnName("contractId");

                entity.Property(e => e.ContractorId).HasColumnName("contractorId");

                entity.HasOne(d => d.Activity)
                    .WithMany(p => p.DetailProjectContractor)
                    .HasForeignKey(d => d.ActivityId)
                    .HasConstraintName("FK__DetailPro__Activ__6E01572D");

                entity.HasOne(d => d.Component)
                    .WithMany(p => p.DetailProjectContractor)
                    .HasForeignKey(d => d.ComponentId)
                    .HasConstraintName("FK__DetailPro__Compo__6D0D32F4");

                entity.HasOne(d => d.Contract)
                    .WithMany(p => p.DetailProjectContractor)
                    .HasForeignKey(d => d.ContractId)
                    .HasConstraintName("FK__DetailPro__contr__693CA210");

                entity.HasOne(d => d.Contractor)
                    .WithMany(p => p.DetailProjectContractor)
                    .HasForeignKey(d => d.ContractorId)
                    .HasConstraintName("FK__DetailPro__contr__6A30C649");

                entity.HasOne(d => d.Element)
                    .WithMany(p => p.DetailProjectContractor)
                    .HasForeignKey(d => d.ElementId)
                    .HasConstraintName("FK__DetailPro__Eleme__6C190EBB");

                entity.HasOne(d => d.HiringData)
                    .WithMany(p => p.DetailProjectContractor)
                    .HasForeignKey(d => d.HiringDataId)
                    .HasConstraintName("FK__DetailPro__Hirin__6B24EA82");

                entity.HasOne(d => d.StatusContractorNavigation)
                    .WithMany(p => p.DetailProjectContractor)
                    .HasForeignKey(d => d.StatusContractor)
                    .HasConstraintName("FK__DetailPro__Statu__5DCAEF64");
            });

            modelBuilder.Entity<DocumentType>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Code).HasMaxLength(5);

                entity.Property(e => e.DocumentType1)
                    .HasMaxLength(100)
                    .HasColumnName("DocumentType");
            });

            modelBuilder.Entity<EconomicdataContractor>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Debt).HasColumnType("money");

                entity.Property(e => e.Freed).HasColumnType("money");

                entity.Property(e => e.Missing).HasColumnType("money");

                entity.Property(e => e.ModifyDate).HasColumnType("date");

                entity.Property(e => e.RegisterDate).HasColumnType("date");

                entity.Property(e => e.TotalPaIdMonth).HasColumnType("money");

                entity.Property(e => e.TotalValue).HasColumnType("money");

                entity.Property(e => e.UnitValue).HasColumnType("money");

                entity.HasOne(d => d.Contract)
                    .WithMany(p => p.EconomicdataContractor)
                    .HasForeignKey(d => d.ContractId)
                    .HasConstraintName("FK__Economicd__Contr__74AE54BC");

                entity.HasOne(d => d.Contractor)
                    .WithMany(p => p.EconomicdataContractor)
                    .HasForeignKey(d => d.ContractorId)
                    .HasConstraintName("FK__Economicd__Contr__73BA3083");
            });

            modelBuilder.Entity<ElementComponent>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Consecutivo)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.NombreElemento).HasMaxLength(100);

                entity.Property(e => e.ObjetoElemento).IsUnicode(false);

                entity.Property(e => e.Recursos).HasColumnType("money");

                entity.Property(e => e.TipoElemento).HasColumnName("tipoElemento");

                entity.Property(e => e.ValorPorDia).HasColumnType("money");

                entity.Property(e => e.ValorPorDiaContratista).HasColumnType("money");

                entity.Property(e => e.ValorTotal).HasColumnType("money");

                entity.Property(e => e.ValorTotalContratista).HasColumnType("money");

                entity.Property(e => e.ValorUnidad).HasColumnType("money");

                entity.HasOne(d => d.Activity)
                    .WithMany(p => p.ElementComponent)
                    .HasForeignKey(d => d.ActivityId)
                    .HasConstraintName("FK__ElementCo__Activ__76969D2E");

                entity.HasOne(d => d.Component)
                    .WithMany(p => p.ElementComponent)
                    .HasForeignKey(d => d.ComponentId)
                    .HasConstraintName("FK__ElementCo__Compo__75A278F5");

                entity.HasOne(d => d.Cpc)
                    .WithMany(p => p.ElementComponent)
                    .HasForeignKey(d => d.CpcId)
                    .HasConstraintName("FK__ElementCo__CpcId__7E37BEF6");

                entity.HasOne(d => d.TipoElementoNavigation)
                    .WithMany(p => p.ElementComponent)
                    .HasForeignKey(d => d.TipoElemento)
                    .HasConstraintName("FK__ElementCo__tipoE__7D439ABD");
            });

            modelBuilder.Entity<ElementType>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Code).HasMaxLength(5);

                entity.Property(e => e.ElementType1)
                    .HasMaxLength(100)
                    .HasColumnName("ElementType");
            });

            modelBuilder.Entity<EmptityHealth>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Emptity)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.TypeEmptity)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.ContractorNavigation)
                    .WithMany(p => p.EmptityHealth)
                    .HasForeignKey(d => d.Contractor)
                    .HasConstraintName("FK__EmptityHe__Contr__5FB337D6");
            });

            modelBuilder.Entity<Files>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.DescriptionFile).HasMaxLength(100);

                entity.Property(e => e.FileType).HasMaxLength(30);

                entity.Property(e => e.FilesName).HasMaxLength(100);

                entity.Property(e => e.MonthPayment).HasMaxLength(10);

                entity.Property(e => e.TypeFilePayment).HasMaxLength(50);

                entity.HasOne(d => d.Contract)
                    .WithMany(p => p.Files)
                    .HasForeignKey(d => d.ContractId)
                    .HasConstraintName("FK__Files__ContractI__00200768");

                entity.HasOne(d => d.Contractor)
                    .WithMany(p => p.Files)
                    .HasForeignKey(d => d.ContractorId)
                    .HasConstraintName("FK__Files__Contracto__01142BA1");

                entity.HasOne(d => d.DocumentTypeNavigation)
                    .WithMany(p => p.Files)
                    .HasForeignKey(d => d.DocumentType)
                    .HasConstraintName("FK__Files__DocumentT__7F2BE32F");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Files)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK__Files__UserId__02084FDA");
            });

            modelBuilder.Entity<Folder>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.FolderName)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.ModifyDate).HasColumnType("date");

                entity.Property(e => e.RegisterDate).HasColumnType("date");

                entity.Property(e => e.TypeFolder).HasMaxLength(30);

                entity.HasOne(d => d.Contract)
                    .WithMany(p => p.Folder)
                    .HasForeignKey(d => d.ContractId)
                    .HasConstraintName("FK__Folder__Contract__6754599E");

                entity.HasOne(d => d.Contractor)
                    .WithMany(p => p.Folder)
                    .HasForeignKey(d => d.ContractorId)
                    .HasConstraintName("FK__Folder__Contract__66603565");
            });

            modelBuilder.Entity<FolderType>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Code).HasMaxLength(5);

                entity.Property(e => e.FolderDescription).HasMaxLength(200);

                entity.Property(e => e.FolderType1)
                    .HasMaxLength(100)
                    .HasColumnName("FolderType");
            });

            modelBuilder.Entity<HiringData>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CargoSupervisorItm).HasMaxLength(100);

                entity.Property(e => e.Caso).HasMaxLength(30);

                entity.Property(e => e.Cdp).HasMaxLength(50);

                entity.Property(e => e.ClaveUsuario).HasMaxLength(15);

                entity.Property(e => e.Compromiso).HasMaxLength(100);

                entity.Property(e => e.Contrato).HasMaxLength(50);

                entity.Property(e => e.FechaDeComite).HasColumnType("date");

                entity.Property(e => e.FechaExaPreocupacional).HasColumnType("date");

                entity.Property(e => e.FechaExpedicionPoliza).HasColumnType("date");

                entity.Property(e => e.FechaFinalizacionConvenio).HasColumnType("date");

                entity.Property(e => e.FechaRealDeInicio).HasColumnType("date");

                entity.Property(e => e.IdentificacionSupervisor).HasMaxLength(50);

                entity.Property(e => e.NoPoliza).HasMaxLength(100);

                entity.Property(e => e.NumeroActa)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.SupervisorItm).HasMaxLength(50);

                entity.Property(e => e.ValorAsegurado)
                    .HasColumnType("money")
                    .HasColumnName("ValorASegurado");

                entity.Property(e => e.VigenciaFinal).HasColumnType("date");

                entity.Property(e => e.VigenciaInicial).HasColumnType("date");

                entity.HasOne(d => d.Contractor)
                    .WithMany(p => p.HiringData)
                    .HasForeignKey(d => d.ContractorId)
                    .HasConstraintName("FK__HiringDat__Contr__656C112C");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.HiringData)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK__HiringDat__UserI__6477ECF3");
            });

            modelBuilder.Entity<MinuteType>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Code).HasMaxLength(5);

                entity.Property(e => e.MinuteType1)
                    .HasMaxLength(100)
                    .HasColumnName("MinuteType");
            });

            modelBuilder.Entity<NewnessContractor>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.RegisterDate).HasColumnType("date");

                entity.HasOne(d => d.Contract)
                    .WithMany(p => p.NewnessContractor)
                    .HasForeignKey(d => d.ContractId)
                    .HasConstraintName("FK__NewnessCo__Contr__797309D9");

                entity.HasOne(d => d.Contractor)
                    .WithMany(p => p.NewnessContractor)
                    .HasForeignKey(d => d.ContractorId)
                    .HasConstraintName("FK__NewnessCo__Contr__787EE5A0");

                entity.HasOne(d => d.NewnessTypeNavigation)
                    .WithMany(p => p.NewnessContractor)
                    .HasForeignKey(d => d.NewnessType)
                    .HasConstraintName("FK__NewnessCo__Newne__7A672E12");
            });

            modelBuilder.Entity<NewnessType>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Code).HasMaxLength(5);

                entity.Property(e => e.NewnessDescription).HasMaxLength(200);

                entity.Property(e => e.NewnessType1)
                    .HasMaxLength(100)
                    .HasColumnName("NewnessType");
            });

            modelBuilder.Entity<Roll>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Code).HasMaxLength(30);

                entity.Property(e => e.RollName)
                    .IsRequired()
                    .HasMaxLength(30);
            });

            modelBuilder.Entity<SharedData>(entity =>
            {
                entity.ToTable("sharedData");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.TypeDataShare).HasMaxLength(30);

                entity.Property(e => e.TypedataRegistered).HasMaxLength(100);
            });

            modelBuilder.Entity<StatusContract>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Code).HasMaxLength(5);

                entity.Property(e => e.StatusContract1)
                    .HasMaxLength(100)
                    .HasColumnName("StatusContract");
            });

            modelBuilder.Entity<StatusContractor>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Code).HasMaxLength(5);

                entity.Property(e => e.StatusContractor1)
                    .HasMaxLength(100)
                    .HasColumnName("StatusContractor");
            });

            modelBuilder.Entity<StatusFile>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Code).HasMaxLength(5);

                entity.Property(e => e.StatusFile1)
                    .HasMaxLength(100)
                    .HasColumnName("StatusFile");
            });

            modelBuilder.Entity<UserFirm>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.OwnerFirm)
                    .HasMaxLength(50)
                    .HasColumnName("ownerFirm");

                entity.Property(e => e.UserCharge).HasMaxLength(100);

                entity.Property(e => e.UserfileName).HasMaxLength(50);

                entity.HasOne(d => d.User)
                    .WithMany(p => p.UserFirm)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK__UserFirm__UserId__7B5B524B");
            });

            modelBuilder.Entity<UserT>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Identification)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.PhoneNumber).HasMaxLength(15);

                entity.Property(e => e.UserEmail)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.UserName)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.UserPassword)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.HasOne(d => d.Roll)
                    .WithMany(p => p.UserT)
                    .HasForeignKey(d => d.RollId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__UserT__RollId__6FE99F9F");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}